# temporary image used as build environment
FROM node:16.13.2-alpine as build


WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# copy required files from context
COPY package.json ./
COPY package-lock.json ./
#copy npmrc template, and any existing .npmrc
COPY .npmrc* ./

# For github package registry access: if a token is supplied, use it to create (possibly overwrite) local .npmrc 
ARG PACKAGEREAD_TOKEN
RUN if [ ${PACKAGEREAD_TOKEN} ]; then (cat .npmrc_template ; echo '${PACKAGEREAD_TOKEN}') > .npmrc ; fi


# download and install node modules
RUN npm install --omit=optional
#RUN npm clean-install --omit=optional

#
RUN rm .npmrc

#copy sources
COPY . ./

#generate ZAViewer bundles
RUN npm run build


# production environment
FROM nginx:stable-alpine

LABEL jp.riken.cau.product="ZAViewer User Interface" \
    jp.riken.cau.version="2.4.0" \
    jp.riken.cau.release-date="2023-01-26"

# copy generated bundles and assets from building stage image
COPY --from=build /app/index.html /usr/share/nginx/html
COPY --from=build /app/assets /usr/share/nginx/html/assets

RUN find /usr/share/nginx/html/ -type d -exec chmod 755 {} \;
RUN find /usr/share/nginx/html/ -type f -exec chmod 644 {} \;

# link to configuration descriptor used when displaying data located in mounted directory
RUN ln -s /usr/share/nginx/html/data/viewer.json /usr/share/nginx/html/viewer.json

# port which NginX listens to 
EXPOSE 80
