# temporary image used as build environment
FROM node:14.15.4-alpine as build


WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# copy required files from context
COPY package.json ./
COPY package-lock.json ./

# download and install build system tool
RUN npm install --global gulp-cli@2.2.0

# download and install node modules
RUN npm install --no-optional
#RUN npm clean-install --no-optional

COPY . ./

#generate ZAViewer bundles
RUN gulp buildprodall

# production environment
FROM nginx:stable-alpine

LABEL jp.riken.cau.product="ZAViewer User Interface" \
    jp.riken.cau.version="2.0.0" \
    jp.riken.cau.release-date="2021-01-06"

# copy generated bundles and assets from building stage image
COPY --from=build /app/index.html /usr/share/nginx/html
COPY --from=build /app/assets /usr/share/nginx/html/assets

# link to configuration descriptor used when displaying data located in mounted directory
RUN ln -s /usr/share/nginx/html/data/viewer.json /usr/share/nginx/html/viewer.json

# port which NginX listens to 
EXPOSE 80
